version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: preschool_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: preschool_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_preschool_data:/var/lib/mysql

volumes:
  mysql_preschool_data: